import React, { useState, useEffect } from "react";
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  ActivityIndicator,
  RefreshControl,
} from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import {
  ArrowLeft,
  DollarSign,
  CheckCircle2,
  TrendingUp,
  Calendar,
  ShieldCheck,
  Building,
  Clock,
} from "lucide-react-native";
import { attendanceService, OFFICE_TIMINGS } from "../../services/attendanceService";
import { SalaryPayslip } from "../../types";

export default function SalaryScreen({ navigation }: { navigation: any }) {
  const [payslips, setPayslips] = useState<SalaryPayslip[]>([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);

  const fetchSalaryData = async () => {
    try {
      const data = await attendanceService.getPayslips();
      setPayslips(data);
    } catch (e) {
      console.log("Salary fetch notice:", e);
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  };

  useEffect(() => {
    fetchSalaryData();
    const unsubscribe = navigation.addListener("focus", () => {
      fetchSalaryData();
    });
    return unsubscribe;
  }, [navigation]);

  const onRefresh = () => {
    setRefreshing(true);
    fetchSalaryData();
  };

  const latest = payslips[0];

  return (
    <SafeAreaView style={styles.container}>
      <View style={styles.header}>
        <TouchableOpacity
          style={styles.backBtn}
          onPress={() => navigation.goBack()}
          activeOpacity={0.7}
        >
          <ArrowLeft size={20} color="#0F172A" />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Salary & Payslips</Text>
        <View style={{ width: 38 }} />
      </View>

      <ScrollView
        contentContainerStyle={styles.scroll}
        refreshControl={
          <RefreshControl refreshing={refreshing} onRefresh={onRefresh} tintColor="#00B050" />
        }
        showsVerticalScrollIndicator={false}
      >
        {/* Latest Payslip Highlight Card */}
        {latest && (
          <View style={styles.highlightCard}>
            <View style={styles.highlightHeader}>
              <Text style={styles.highlightTag}>Latest Disbursed Salary</Text>
              <View style={styles.paidBadge}>
                <CheckCircle2 size={12} color="#4ADE80" />
                <Text style={styles.paidBadgeText}> {latest.paymentStatus || "PAID"}</Text>
              </View>
            </View>

            <Text style={styles.highlightPeriod}>
              {latest.month} {latest.year}
            </Text>
            <Text style={styles.highlightAmount}>${latest.netPayable.toLocaleString()}</Text>
            <Text style={styles.highlightSub}>Net Take-Home Pay (Bank Direct Deposit)</Text>

            <View style={styles.breakdownBox}>
              <View style={styles.breakdownRow}>
                <Text style={styles.breakdownLabel}>Basic Salary</Text>
                <Text style={styles.breakdownVal}>${latest.basicSalary.toLocaleString()}</Text>
              </View>
              <View style={styles.breakdownRow}>
                <Text style={styles.breakdownLabel}>House & Medical Allowances</Text>
                <Text style={styles.breakdownVal}>
                  +${(latest.houseRent + latest.medicalAllowance).toLocaleString()}
                </Text>
              </View>
              <View style={styles.breakdownRow}>
                <Text style={styles.breakdownLabel}>
                  Approved Overtime Pay (@${OFFICE_TIMINGS.overtimeRatePerHour}/hr)
                </Text>
                <Text style={[styles.breakdownVal, { color: "#4ADE80" }]}>
                  +${latest.overtimePay.toLocaleString()}
                </Text>
              </View>
              <View style={styles.breakdownRow}>
                <Text style={styles.breakdownLabel}>Taxes & Provident Fund</Text>
                <Text style={[styles.breakdownVal, { color: "#FB7185" }]}>
                  -${(latest.taxDeduction + latest.providentFund).toLocaleString()}
                </Text>
              </View>
            </View>
          </View>
        )}

        <Text style={styles.sectionTitle}>Disbursement History</Text>

        {loading ? (
          <ActivityIndicator color="#00B050" size="large" style={{ marginTop: 20 }} />
        ) : payslips.length === 0 ? (
          <View style={styles.emptyBox}>
            <DollarSign size={44} color="#94A3B8" />
            <Text style={styles.emptyTitle}>No Disbursed Payslips</Text>
            <Text style={styles.emptySubtitle}>
              Monthly salary batches generated by HR / Payroll manager will appear here.
            </Text>
          </View>
        ) : (
          payslips.map((ps, idx) => (
            <View key={ps.id || idx} style={styles.historyCard}>
              <View style={styles.historyLeft}>
                <Text style={styles.historyMonth}>
                  {ps.month} {ps.year}
                </Text>
                <Text style={styles.historyDate}>Disbursed on {ps.paymentDate || "1st of month"}</Text>
              </View>
              <View style={styles.historyRight}>
                <Text style={styles.historyAmount}>${ps.netPayable.toLocaleString()}</Text>
                <Text style={styles.historyStatus}>✓ {ps.paymentStatus}</Text>
              </View>
            </View>
          ))
        )}
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F8FAFC",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F5F9",
    backgroundColor: "#FFFFFF",
  },
  backBtn: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: "#F1F5F9",
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#0F172A",
  },
  scroll: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 36,
  },
  highlightCard: {
    backgroundColor: "#0F172A",
    borderRadius: 24,
    padding: 22,
    marginBottom: 24,
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 4,
  },
  highlightHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  highlightTag: {
    color: "#94A3B8",
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  paidBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "rgba(34, 197, 94, 0.2)",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(34, 197, 94, 0.4)",
  },
  paidBadgeText: {
    color: "#4ADE80",
    fontSize: 10,
    fontWeight: "800",
  },
  highlightPeriod: {
    color: "#F8FAFC",
    fontSize: 16,
    fontWeight: "800",
  },
  highlightAmount: {
    color: "#FFFFFF",
    fontSize: 34,
    fontWeight: "900",
    marginVertical: 4,
    letterSpacing: -0.5,
  },
  highlightSub: {
    color: "#94A3B8",
    fontSize: 12,
    marginBottom: 16,
  },
  breakdownBox: {
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.1)",
    paddingTop: 14,
  },
  breakdownRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 5,
  },
  breakdownLabel: {
    color: "#CBD5E1",
    fontSize: 12,
    fontWeight: "500",
  },
  breakdownVal: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "700",
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: "800",
    color: "#0F172A",
    marginBottom: 12,
  },
  historyCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    marginBottom: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.02,
    shadowRadius: 6,
    elevation: 1,
  },
  historyLeft: {},
  historyMonth: {
    fontSize: 14,
    fontWeight: "800",
    color: "#0F172A",
  },
  historyDate: {
    fontSize: 11,
    color: "#64748B",
    marginTop: 2,
  },
  historyRight: {
    alignItems: "flex-end",
  },
  historyAmount: {
    fontSize: 15,
    fontWeight: "900",
    color: "#0F172A",
  },
  historyStatus: {
    fontSize: 11,
    fontWeight: "800",
    color: "#00B050",
    marginTop: 2,
  },
  emptyBox: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 50,
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  emptyTitle: {
    fontSize: 15,
    fontWeight: "800",
    color: "#0F172A",
    marginTop: 12,
  },
  emptySubtitle: {
    fontSize: 12,
    color: "#64748B",
    textAlign: "center",
    marginTop: 4,
    paddingHorizontal: 24,
    lineHeight: 16,
  },
});
